[package]
name = "hello-cargo-sample"
version = "0.1.0"
authors = ["Gatsby Lee <thewayofthinking@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
